version: '3.8'
services:
  #mongodb:
    #image: mongo:4.4
    #container_name: mongodb
    #ports:
      #- "27017:27017"
    #volumes:
      #- mongo-data:/data/db

  node-app:
    build: ./node-app
    #depends_on:
      #- mongodb
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/declic
    volumes:
      - ./node-app:/app

  spring-app:
    build: ./spring-app
    ports:
      - "9090:9090"
    volumes:
      - ./spring-app:/app

volumes:
  mongo-data:
